CREATE TABLE purchases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   customer_id BIGINT,
   CONSTRAINT pk_purchases PRIMARY KEY (id)
);

ALTER TABLE purchases ADD CONSTRAINT FK_PURCHASES_ON_USER FOREIGN KEY (customer_id) REFERENCES customers (id);

INSERT
INTO
  purchases
  (created_at, customer_id)
VALUES
  (NOW(), 1);