CREATE TABLE purchase_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   purchase_id BIGINT,
   product_id BIGINT,
   product_count DOUBLE PRECISION NOT NULL,
   product_price DOUBLE PRECISION NOT NULL,
   CONSTRAINT pk_purchase_products PRIMARY KEY (id)
);

ALTER TABLE purchase_products ADD CONSTRAINT FK_PURCHASE_PRODUCTS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE purchase_products ADD CONSTRAINT FK_PURCHASE_PRODUCTS_ON_PURCHASE FOREIGN KEY (purchase_id) REFERENCES purchases (id);

INSERT
INTO
  purchase_products
  (purchase_id, product_id, product_count, product_price)
VALUES
  (1, 1, 3, 89);