CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   CONSTRAINT pk_categories PRIMARY KEY (id)
);

INSERT
INTO
  categories
  (name)
VALUES
  ('Fruit');