CREATE TABLE warehouse (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   product_id BIGINT,
   amount INTEGER,
   CONSTRAINT pk_warehouse PRIMARY KEY (id)
);

INSERT
INTO
  warehouse
  (product_id, amount)
VALUES
  (1, 8);
