CREATE TABLE customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   username VARCHAR(255),
   password VARCHAR(255),
   CONSTRAINT pk_users PRIMARY KEY (id)
);

INSERT
INTO
  customers
  (username, password)
VALUES
  ('1', '$2y$10$STINJm09S9w8g3QdicOBJekl5kmyR8rfPSZFanUXifqQn0CBodkra'),
  ('2', '$2y$10$STINJm09S9w8g3QdicOBJekl5kmyR8rfPSZFanUXifqQn0CBodkra');